# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-02-14 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20190207_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssh_log',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'webssh'), (2, 'Xshell'), (3, 'SecureCRT')], default=1, null=True, verbose_name='\u7ec8\u7aef\u7c7b\u578b'),
        ),
    ]
